language: python
python:
  - "3.4"
before_install:
  - sudo apt-get install -y libgexiv2-dev libyaml-dev python3-gobject
virtualenv:
  system_site_packages: true
install: pip install -r requirements.txt
script: make test

# Local Variables:
# mode: yaml
# End:
